### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by JorensM** [isaurssaurav/hot-reload-extension-vite-plugin#8] opened 2024-02-09 09:54 UTC
Hello, thanks for creating this plugin, it would be a godsend *if* I could actually get it to work.

So I have a vanilla Vite app with 2 files - `navkeys.js` and `worker.ts`. Worker file just console.logs a message, and navkeys is the file of my chrome extension. I have the `NODE_ENV` set to `development` (confirmed with a console.log), and the following is my Vite config:

```
import hotReloadExtension from 'hot-reload-extension-vite';
import { defineConfig } from 'vite';

export default defineConfig({
    build: {
        rollupOptions: {
            input: './src/navkeys.js',
            output: {
                assetFileNames: '[name].[ext]',
                entryFileNames: '[name].js'
            }
        }
    },
    plugins: [
        hotReloadExtension({
        log: true,
          backgroundPath: 'src/worker.ts' // src/pages/background/index.ts
        })
    ]
});
```

Thank you very much! If there's more info you need let me know!

**Comment by captn-d** [comment] 2024-02-10 21:46
Same for me, the changes of my content script are correctly watched (`dist` dir is rebuilt), however those changes are not reflected in the UI on the web page (my extension adds DOM elements on the page, from content script).
The web page needs to be reloaded (reloading extension from `chrome://extensions/` has no effect).
It still saves me some time since I don't have to `npm run build` every time but it does not work like shown on the demo video.

- hot-reload-extension-vite: 1.0.13
- vite: 5.1.0
- Chrome 121.0.6167.161
- node v20.11.0
- Windows 11

**Comment by isaurssaurav** [comment] 2024-02-11 14:07
@JorensM ,

I already see the problem in your vite config file. You should pass the `src/worker.ts` to build option. So, your vite config should look something like below:

```
import hotReloadExtension from 'hot-reload-extension-vite';
import { defineConfig } from 'vite';

export default defineConfig({
    build: {
        rollupOptions: {
            input: {
                    navkeys:'./src/navkeys.ts',
                    worker: './src/worker.ts'
             },
            output: {
                assetFileNames: '[name].[ext]',
                entryFileNames: '[name].js'
            }
        }
    },
    plugins: [
        hotReloadExtension({
        log: true,
          backgroundPath: 'src/worker.ts' // src/pages/background/index.ts
        })
    ]
});
```
The reason being the reload script is added to your server worker on build time on dev environment.

After this donot forget to add the built service worker into manifest.
```
// manifest.json

{
    "manifest_version": 3,
     //..... other stuff
    "background": { "service_worker": "./worker.js" } // add this line
}
```

And lastly make sure your pass NODE_ENV as development.

Let me know if it works.

**Comment by JorensM** [comment] 2024-02-11 14:13
@isaurssaurav I'm already importing the worker from `navkeys.js` and the console.log in my `worker.ts` confirms that it's being imported. But I haven't added the worker to the manifest, I'll try that and report back

**Comment by isaurssaurav** [comment] 2024-02-11 14:19
@captn-d,

Could you provide me with some example code so that I could help you better 😄 ?. You could also go to the [example](https://github.com/isaurssaurav/hot-reload-extension-vite-plugin/tree/main/example) directory of this project to see if you are missing some configs. The example project works with this `hot-reload-extension-vite-plugin` and demo video is actually started with example project as starter project file.

**Comment by isaurssaurav** [comment] 2024-02-11 14:30
@JorensM ,

Service worker file should be built separately and you cannot import service worker in other context of your extension. It will not work. Please do follow above `vite.config` file i suggested.

**Comment by isaurssaurav** [comment] 2024-03-03 20:16
Closing this issue as it is related more to the misconfiguration of vite's config file than the actual bug in the pakage.

Feel free to open the new issue incase the issue is not resolved.

**Closed by isaurssaurav** 2024-03-03 20:16 UTC

**Comment by dhzhme** [comment] 2024-08-19 07:10
Hello, this is my configs, it also not working yet.
```ts
import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
import hotReloadExtension from 'hot-reload-extension-vite';

export default defineConfig({
  plugins: [
    react(),
    hotReloadExtension({
      log: true,
      backgroundPath: 'src/background/index.ts',
    }),
  ],
  build: {
    rollupOptions: {
      input: {
        options: resolve(__dirname, 'options.html'),
        test: resolve(__dirname, 'test.html'),
        side_panel: resolve(__dirname, 'side-panel.html'),
        service_worker: resolve(__dirname, 'src/background/index.ts'),
        content_script: resolve(__dirname, 'src/content-script.ts'),
      },
      output: {
        chunkFileNames: '[name].[hash].js',
        assetFileNames: '[name].[hash].[ext]',
        entryFileNames: '[name].js',
        dir: 'dist',
      },
    },
  },
});
```
```json
{
  "manifest_version": 3,
  "name": "MVP",
  "description": "MVP Extension",
  "version": "1.0",
  "icons": {
    "16": "images/icon-16.png",
    "32": "images/icon-32.png",
    "48": "images/icon-48.png",
    "128": "images/icon-128.png"
  },
  "options_ui": {
    "page": "options.html",
    "open_in_tab": true
  },
  "action": {
    "default_title": "点击打开插件! haha"
  },
  "commands": {
    "_execute_action": {
      "suggested_key": {
        "default": "Ctrl+B",
        "mac": "Command+B"
      }
    }
  },
  "content_scripts": [
    {
      "matches": ["https://news.ycombinator.com/*", "http://*/*", "https://*/*"],
      "js": ["content_script.js"]
    }
  ],
  "background": {
    "type": "module",
    "service_worker": "service_worker.js"
  },
  "permissions": [
    "storage",
    "declarativeContent",
    "activeTab",
    "notifications",
    "sidePanel",
    "contextMenus",
    "tabs",
    "activeTab",
    "cookies",
    "scripting",
    "downloads",
    "history"
  ],
  "side_panel": {
    "default_path": "side-panel.html"
  },
  "host_permissions": ["http://*/*", "https://*/*"]
}
```
